version: "3.2"
services: 
  api:
    image: microsoft/dotnet:sdk
    volumes:
      - type: bind
        source: ./api/
        target: /app
        volume: 
          nocopy: true
    entrypoint: dotnet watch --project /app/api.csproj run
    ports:
      - "5000:5000"

  # db:
  #   image: microsoft/mssql-server-linux
  #   ports: 
  #     - 1433:1433
  #   environment:
  #     - ACCEPT_EULA=Y
  #     - MSSQL_PID=Express
  #     - SA_PASSWORD=correctHorseBatteryStaple1