version: "3.2"
services: 
  api:
    image: microsoft/dotnet:sdk
    volumes:
      - ./api/:/app
    ports:
      - "5000:5000"
    entrypoint: dotnet watch --project /app/api.csproj run
  web:
    image: teracy/angular-cli
    working_dir: /app
    volumes:
      - ./web/docker4devs/:/app
    ports:
      - "4200:4200"
    entrypoint: ng serve --watch --host 0.0.0.0 --port 4200

  # db:
  #   image: microsoft/mssql-server-linux
  #   ports: 
  #     - 1433:1433
  #   environment:
  #     - ACCEPT_EULA=Y
  #     - MSSQL_PID=Express
  #     - SA_PASSWORD=correctHorseBatteryStaple1