version: "3.2"
services: 
  api:
    image: mcr.microsoft.com/dotnet/core/sdk:2.1
    working_dir: /app/api/
    volumes:
      - ./api/:/app/api/
    ports:
      - "5000:5000"
    entrypoint: dotnet watch --project /app/api/api.csproj run
    depends_on:
      - db
  web:
    image: teracy/angular-cli
    working_dir: /app/web/
    volumes:
      - ./web/docker4devs/:/app/web/
    ports:
      - "8080:8080"
    entrypoint: npm run serve
    depends_on:
      - api
  db:
    image: microsoft/mssql-server-linux
    ports: 
      - 1433:1433
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_PID=Express
      - MSSQL_DB=docker4devDB
      - MSSQL_USER=sa
      - MSSQL_PASSWORD=correctHorseBatteryStaple1
      - SA_PASSWORD=correctHorseBatteryStaple1